language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - "8"
before_install:
  - "npm i -g tiddlywiki@5.1.14"
  - "git clone https://github.com/danielo515/tw5-pouchdb.git pouchdb" # note that I'm naming the output folders for easier reference later
  - "git clone https://github.com/danielo515/tiddlypouch.git tpouch"
  - "ls -l"
before_script:
 - export TIDDLYWIKI_PLUGIN_PATH="$(pwd)/pouchdb/src/plugins:$(pwd)/tpouch/dist:$(pwd)/plugins" # Plugins paths with all deps globally available
 - "(cd tpouch && npm i && gulp travis --production)"
script:
 - npm run build-plugin # builds NoteSelf core plugins
 - tiddlywiki ./wiki --verbose --build index --build OnlineDemo --build favicon --build library
 - tiddlywiki ./editions/developer --verbose --build index # build the developer edition
 - "(cd ./tpouch && gulp travis)" # Build non minified version of TPouch code ( no --production flag )
 - tiddlywiki ./wiki --verbose --build develop # This is the same as the online one, but to a different dist path
 # ===== Build the edge version with the latest version of tiddlywiki just to see if it works at all =====
 - "npm i tiddlywiki@latest  && npx tiddlywiki --version"
 - "npx tiddlywiki ./editions/edge --verbose --build index " # build the edge edition (includes not well tested stuff)
 - cp -r ./wiki/output/* ./dist/ # Copy everything to the dist directory
 # Measures file sizes and adds that data to the pull request
 - python node_modules/travis-weigh-in/weigh_in.py dist/online/index.html 
 - python node_modules/travis-weigh-in/weigh_in.py dist/dev/index.html 
 - python node_modules/travis-weigh-in/weigh_in.py dist/index.html
 - "ls -lR dist"
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: ./dist
  target_branch: master
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: develop
