language: node_js
node_js:
  - "6"
before_install:
  - "git clone https://github.com/Jermolene/TiddlyWiki5.git tw5"
  - "(cd tw5 && npm link)"
before_script:
 - "git clone https://github.com/danielo515/tiddlypouch.git tpouch"
 - "(cd tpouch && npm i && npm link tiddlywiki && gulp --production)"
 - export TIDDLYWIKI_PLUGIN_PATH="$(pwd)/tpouch/dist"
 - "git clone https://github.com/NoteSelf/NoteSelf.github.io.git noteself"
 - cd noteself
 - "git checkout develop"
script:
 - tiddlywiki ./wiki --verbose --build index --build OnlineDemo --build favicon --build library
 - cp -r ./wiki/output/* ../dist/
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: ../dist
  target_branch: master
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: develop